# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - gptsmartsearch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            . 
            !venv/

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      
      - uses: Azure/login@v1
        with:
          creds: '{"clientId":"7051c641-c62b-40a6-b6cb-ab69f685342f","clientSecret":"lz.8Q~xBxiD81Zau5KR3OZK_8IZX12R-DZjtFbfJ","subscriptionId":"0b0d40a3-9e2b-4c48-a57b-a45b9ce3bdda","tenantId":"c023101b-be0d-4a03-991a-824f9032469a"}'
      
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: 7051c641-c62b-40a6-b6cb-ab69f685342f
          tenant-id: c023101b-be0d-4a03-991a-824f9032469a
          subscription-id: 0b0d40a3-9e2b-4c48-a57b-a45b9ce3bdda
  
      - name: 'Run az commands'
        run: |
          az account show
          az group list
          pwd 
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'gptsmartsearch'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8B4D93752E3B47E6A81BC15375068C6F }}
